# Generated by Django 4.1.7 on 2023-04-18 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_side', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_disabe',
            field=models.BooleanField(default=False),
        ),
    ]
